name: Fresh Machine, Clone Git Repo, Lists then AWS S3
on: 
    push:
        branches: [main]
    pull_request:
        branches: [main]
jobs:
  JobForClone:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning Current Repo
        uses: actions/checkout@v3
      - name: Lets Conform
        run: |
            ls $pwd
            ls ~ 
